### ISSUE TITLE
mongo_setup and panel modules missing

### ISSUE THREAD

**Issue by prubbens** [burtonrj/CytoPy#12]
The `mongo_setup` and `panel` modules seem to be missing from the `data` directory. 

As I haven't been able to connect to MongoDB, this probably is the reason why I get the error: `ConnectionFailure: Connection with alias "core" has not been defined`?

**Comment by burtonrj** [comment]
I'm not seeing any issues with imports from `data` on my end. Are you sure pymongo and mongoengine have been installed properly? Can you connect to MongoDB external of CytoPy?

Typing `mongod` into your terminal should bring up the mongodb console. I also like the Robo3t software as a GUI to mongodb: https://robomongo.org/download

**Comment by prubbens** [comment]
Never worked with MongoDB before, although I have installed the prerequisites according to the instructions of CytoPy. 

Typing in `mongod` does not open a console (although it is installed). Robo3t opens but I am not able to establish a connection to a localhost. 

However, what I meant to say is that mongo_setup.py and panel.py is not part of the environment that is installed when running the .yml file. Is this due to the fact that I don't have a proper MongoDB connection (although software is installed on the laptop)?

**Comment by burtonrj** [comment]
I think there is some confusion, are you using the updated release? mongo_setup.py has been renamed to setup.py and panel.py has been merged with experiment.py. That is why these environments no longer exist.

I think the issue you are having is either:

- `global_init` has not been called and a connection not established before using the other functionality in CytoPy, or
- MongoDB server is not running on your local system

The first is easy, before you do anything in CytoPy (so at the top of your script) you should import `global_init` from `CytoPy.data.setup` and call this function with a database name e.g. `global_init(database_name='my_new_database')`. This will setup a connection to the database so you can start working. Do this every time you run CytoPy.

Alternatively, if that isn't working and you can't establish a connection to MongoDB with Robo3t, that suggests that there is a problem with your setup. What operating system are you running so I can point you to the right information?

**Comment by prubbens** [comment]
That explains some of the confusion :). I'm following the instructions from here: https://cytopy.readthedocs.io/en/latest/2_project.html, which probably is not yet updated for the newest version. 

I indeed am having some problems with connecting to MongoDB as well, so I guess I have not properly installed it. I am working on Ubuntu 18.04.

**Comment by burtonrj** [comment]
Ah! I thought I had updated that page but obviously missed this! Thank you for bringing this to my attention. Will change that now. Just for clarification for the time being, those imports should be:
`from CytoPy.data.setup import global_init`
`from CytoPy.data.experiment import panel`

Thats great! Life is easier on linux for this stuff. If you try running the following:
`sudo systemctl start mongod`
`sudo systemctl status mongod`

Let me know what type of error message you get (if any) and I'll try to guide you through it

**Comment by prubbens** [comment]
Ok great! Want to this over a separate issue or email?

**Comment by burtonrj** [comment]
Happy to continue by email. For anyone visiting in the future, please see https://docs.mongodb.com/manual/administration/install-community/ for details regarding MongoDB installation
