### ISSUE TITLE
Pip backtracking - pip is looking at multiple versions of...

### ISSUE THREAD

**Issue by plopezgarcia** [burtonrj/CytoPy#18]
First of all, great job!

I have been trying to install CytoPy on MacOS and this is the first time I encounter this problem. Yesterday I spent over 30 minutes without success with pipenv (which shows no logs) with the CPU maxed out.

Today I repeated the process with pip to see logs and it seems the issue is related to  **pip backtracking**. For every dependency, pip is showing: ```pip is looking at multiple versions of...``` and then downloads dozens past versions of each python module and takes forever to decide which one to pick (CPU maxed at 99%).

Any ideas on how to fix this? I checked the documentation but there is nothing related to this. I never had this issue before.

Thanks in advance.

**Comment by burtonrj** [comment]
Hi,

Thanks for your kind comments and sorry you're having issues. CytoPy is still maturing at the moment. I have a new release coming in the next week (just finishing up documentation and integration tests). I've been refactoring the setup script to make installation easier, as I'm aware CytoPy has some heavy dependencies. There will also be a docker image with the new release which might help with trying CytoPy out before committing to a local installation.

I have to admit this is the first time I've seen a pip backtracking issue...I would say watch out for the new release and see if this resolves the problem. I'll leave this issue open for now and come back to it once the new release is up.

Again, apologises for any frustrations and time wasted,
Ross

**Comment by plopezgarcia** [comment]
Thanks a lot for the quick reply Ross!

If this helps, I did some more tests also on Ubuntu and and had the same issue when inside a virtual environment (tried pipenv and virtualenv).

However, it *did work* if pip install is done at system level, not within a virtual environment.

I hope this helps somehow...

**Comment by burtonrj** [comment]
Hmmm...very strange. During development and for our manuscript I've been using conda. I have to admit I haven't done exhaustive tests with pipenv and virtualenv, but I'll add this to the todo list. There are some tricky dependency issues that I've ironed out in the new release which might be causing pip backtracking problems: notably conflicts between HDBSCAN and Tensorflow with their supported [https://github.com/scikit-learn-contrib/hdbscan/issues/457](Numpy version). 

The plan is to use [https://python-poetry.org/docs/](poetry) and a toml file for the upcoming release to create my own wheel, should solve a lot of these headaches!

**Comment by burtonrj** [comment]
Closing this issue because it refers to the previous release. Additionally latest commit offers docker-compose solution for tackling dependency and install issues.
