### ISSUE TITLE
FlowUtils update

### ISSUE THREAD

**Issue by whitews** [burtonrj/CytoPy#27]
Hey Ross,

FlowUtils has been updated to address the issue of having to preinstall NumPy. The newest version (0.9.3) is up on PyPI. If you could, please test it out and let me know if it's working for CytoPy.

Kind regards,
Scott

**Comment by burtonrj** [comment]
Thanks Scott, tested this today and it works. Will bump up to 0.9.3 in the next release of CytoPy that should be out soon.
