### ISSUE TITLE
Issues with saving new project to local database

### ISSUE THREAD

**Issue by connorcall** [burtonrj/CytoPy#32]
Hi, I'm trying to develop a new flow data analysis protocol using CytoPy, but I seem to be having troubles getting a project successfully set up. I am going through the tutorials and I can set up a local database and project, but then if I try to save, I get a timeout error every time. 

Are there stipulations on what types of connections are needed to form databases? All I have so far is:

from cytopy.data import setup,project

setup.global_init("test")

newproject = project.Project(project_id = 'testproj',data_directory = "/Users/connorcall/Desktop/testdata")
newproject.save()

and I get the following error:
ServerSelectionTimeoutError: localhost:27017: [Errno 61] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 62a7abb9c1f069dabb0789b8, topology_type: Single, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 61] Connection refused')>]>

Thanks for any help you can offer!

**Comment by jfgonsalves** [comment]
Hi there, are you using the Docker image or manual install?

**Comment by connorcall** [comment]
I did a manual install and set up a new conda enviornment.

**Comment by jfgonsalves** [comment]
Okay, did you install MongoDB with Homebrew? (I’m assuming you are on a Mac judging by your Home folder structure?).

>

**Comment by connorcall** [comment]
ah, I found out there was an error in the MongoDB install. Thank you for your help!

**Comment by jfgonsalves** [comment]
Are you using the default Dockercompose file?

Maybe try use the latest version of of MongoDB rather than the old image that the compose file requests.

Change "4.4-bionic" to "latest"

**Comment by leeanapeters** [comment]
I do have 4.4 bionic so I will try that, thank you!
________________________________
