### ISSUE TITLE
ModuleNotFoundError: No module named 'setuptools'

### ISSUE THREAD

**Issue by md716alam** [burtonrj/CytoPy#5]
Installed setuptools version :47.1.1

WARNING: Missing build requirements in pyproject.toml for git+https://github.com/burtonrj/CytoPy.git.                                                                   WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'setuptools>=40.8.0' and 'wheel'.                                 Getting requirements to build wheel ... done                                                                                                                          ERROR: Exception:                                                                                                                                                       Traceback (most recent call last):                                                                                                                                        File "C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\cyto\lib\site-packages\pip\_internal\cli\base_command.py", line 188, in _main                                status = self.run(options, args)                                                                                                                                      File "C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\cyto\lib\site-packages\pip\_internal\cli\req_command.py", line 185, in wrapper                               return func(self, options, args)                                                                                                                                      File "C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\cyto\lib\site-packages\pip\_internal\commands\install.py", line 333, in run                                  reqs, check_supported_wheels=not options.target_dir                                                                                                                   File "C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\cyto\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 179, in resolve                    discovered_reqs.extend(self._resolve_one(requirement_set, req))                                                                                                       File "C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\cyto\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 362, in _resolve_one               abstract_dist = self._get_abstract_dist_for(req_to_install)                                                                                                           File "C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\cyto\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 314, in _get_abstract_dist_for     abstract_dist = self.preparer.prepare_linked_requirement(req)                                                                                                         File "C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\cyto\lib\site-packages\pip\_internal\operations\prepare.py", line 488, in prepare_linked_requirement         req, self.req_tracker, self.finder, self.build_isolation,                                                                                                             File "C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\cyto\lib\site-packages\pip\_internal\operations\prepare.py", line 91, in _get_prepared_distribution          abstract_dist.prepare_distribution_metadata(finder, build_isolation)                                                                                                  File "C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\cyto\lib\site-packages\pip\_internal\distributions\sdist.py", line 38, in prepare_distribution_metadata      self._setup_isolation(finder)                                                                                                                                         File "C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\cyto\lib\site-packages\pip\_internal\distributions\sdist.py", line 96, in _setup_isolation                   reqs = backend.get_requires_for_build_wheel()                                                                                                                         File "C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\cyto\lib\site-packages\pip\_vendor\pep517\wrappers.py", line 161, in get_requires_for_build_wheel            'config_settings': config_settings                                                                                                                                    File "C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\cyto\lib\site-packages\pip\_vendor\pep517\wrappers.py", line 265, in _call_hook                              raise BackendUnavailable(data.get('traceback', ''))                                                                                                                 pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):                                                                                        File "C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\cyto\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 86, in _build_backend                        obj = import_module(mod_path)                                                                                                                                         File "C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\cyto\lib\importlib\__init__.py", line 127, in import_module                                                  return _bootstrap._gcd_import(name[level:], package, level)                                                                                                           File "<frozen importlib._bootstrap>", line 1006, in _gcd_import                                                                                                         File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                                                                       File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked                                                                                              File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                                                                            File "<frozen importlib._bootstrap>", line 1006, in _gcd_import                                                                                                         File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                                                                       File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked                                                                                            ModuleNotFoundError: No module named 'setuptools'

**Comment by burtonrj** [comment]
Hi, this seems to be a PEP 518 issue. I've updated pyproject.toml to specify the version of steruptools and wheel requirements. I also suggest updating pip before trying to install again.

**Comment by md716alam** [comment]
Thanks, 
above issue is fixed , but one error is coming .

Collecting Shapely==1.6.4.post2                                                                                                                                           Using cached Shapely-1.6.4.post2.tar.gz (225 kB)                                                                                                                          ERROR: Command errored out with exit status 1:                                                                                                                           command: 'C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\cyto\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tauala\\AppData\\Local\\Temp\\pip-install-mo4iqzfk\\Shapely\\setup.py'"'"'; __file__='"'"'C:\\Users\\tauala\\AppData\\Local\\Temp\\pip-install-mo4iqzfk\\Shapely\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\tauala\AppData\Local\Temp\pip-pip-egg-info-yj28a3en'                                                                                                           cwd: C:\Users\tauala\AppData\Local\Temp\pip-install-mo4iqzfk\Shapely\                                                                                              Complete output (9 lines):                                                                                                                                              Traceback (most recent call last):                                                                                                                                        File "<string>", line 1, in <module>                                                                                                                                    File "C:\Users\tauala\AppData\Local\Temp\pip-install-mo4iqzfk\Shapely\setup.py", line 80, in <module>                                                                     from shapely._buildcfg import geos_version_string, geos_version, \                                                                                                    File "C:\Users\tauala\AppData\Local\Temp\pip-install-mo4iqzfk\Shapely\shapely\_buildcfg.py", line 200, in <module>                                                        lgeos = CDLL("geos_c.dll")                                                                                                                                            File "C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\cyto\lib\ctypes\__init__.py", line 364, in __init__                                                          self._handle = _dlopen(self._name, mode)                                                                                                                            OSError: [WinError 126] The specified module could not be found                                                                                                         ----------------------------------------                                                                                                                            ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by burtonrj** [comment]
These sounds like a Conda issue. For now, run the following:

`conda install -c conda-forge shapely`

Then try and install CytoPy again.

I'll work on the setup to extend support for Anaconda.

**Comment by md716alam** [comment]
Thanks lot,
I have installed successfully cytopy.

**Comment by burtonrj** [comment]
No problem, enjoy!
