### ISSUE TITLE
Error in EvaluateBatchEffects

### ISSUE THREAD

**Issue by rahusomavanshi** [burtonrj/CytoPy#7]
Hi, 

I am trying to install and use CytoPy. However, I have encountered following error - 

Traceback (most recent call last):
  File "CytoZoetis.py", line 58, in <module>
    batch_effect = EvaluateBatchEffects(experiment=experiment,
NameError: name 'EvaluateBatchEffects' is not defined

I request you to please resolve it.

Thanks and Regards,

Rahul

**Comment by burtonrj** [comment]
Have you imported the EvaluateBatchEffects class?

`from CytoPy.flow.batch_effects import EvaluateBatchEffects`

**Comment by rahusomavanshi** [comment]
I hadn't imported that. It worked after import. 
Sorry for inconvinience.
